### ISSUE TITLE
Rešitve nalog iz razdelka 1: Zahtevnost algoritmov

### ISSUE THREAD

**Issue by jaanos** [jaanos/or-zbirka#1]
- [x] 1.1. [`zrcaljenje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zrcaljenje.tex)
- [x] 1.2. [`stevec`](https://github.com/jaanos/or-zbirka/blob/master/naloge/stevec.tex)
- [x] 1.3. [`bubblesort`](https://github.com/jaanos/or-zbirka/blob/master/naloge/bubblesort.tex)
- [x] 1.4. [`mergesort`](https://github.com/jaanos/or-zbirka/blob/master/naloge/mergesort.tex)
- [x] 1.5. [`razcep`](https://github.com/jaanos/or-zbirka/blob/master/naloge/razcep.tex)
- [x] 1.6. [`korenski`](https://github.com/jaanos/or-zbirka/blob/master/naloge/korenski.tex)
- [x] 1.7. [`alg`](https://github.com/jaanos/or-zbirka/blob/master/naloge/alg.tex)
- [x] 1.8. [`onotacija`](https://github.com/jaanos/or-zbirka/blob/master/naloge/onotacija.tex) - @kuco23 (#19)
- [x] 1.9. [`usmerjentrikotnik`](https://github.com/jaanos/or-zbirka/blob/master/naloge/usmerjentrikotnik.tex) (10f7371)
- [x] 1.10. [`reverse`](https://github.com/jaanos/or-zbirka/blob/master/naloge/reverse.tex) (b5b7bc9)
- [x] 1.11. [`hamilton`](https://github.com/jaanos/or-zbirka/blob/master/naloge/hamilton.tex) (7b7e9f5)
- [x] 1.12. [`reversestart`](https://github.com/jaanos/or-zbirka/blob/master/naloge/reversestart.tex) (66da36c)
- [x] 1.13. [`kosi`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kosi.tex) (e1b00ee)
- [x] 1.14. [`zlivanje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zlivanje.tex) (df0aed2)
- [x] 1.15. [`sistem`](https://github.com/jaanos/or-zbirka/blob/master/naloge/sistem.tex) (bd48d14)
- [x] 1.16. [`preurejanje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/preurejanje.tex) (f49bd1e)

Če bi kdo rad rešil katero nalogo, naj prosim odgovori na ta issue in si jo tako rezervira.

**Comment by kuco23** [comment]
Pozdravljeni, rezerviral bi nalogo 1.8.

**Comment by jaanos** [comment]
@kuco23, imaš rezervirano nalogo 1.8.
