### ISSUE TITLE
Rešitve nalog iz razdelka 2: Celoštevilsko linearno programiranje

### ISSUE THREAD

**Issue by jaanos** [jaanos/or-zbirka#2]
- [x] 2.1. [`proj`](https://github.com/jaanos/or-zbirka/blob/master/naloge/proj.tex)
- [x] 2.2. [`proj2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/proj2.tex)
- [x] 2.3. [`skladisca`](https://github.com/jaanos/or-zbirka/blob/master/naloge/skladisca.tex)
- [x] 2.4. [`dominacija`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dominacija.tex)
- [x] 2.5. [`maxprirejanje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/maxprirejanje.tex)
- [x] 2.6. [`najkrajsapot`](https://github.com/jaanos/or-zbirka/blob/master/naloge/najkrajsapot.tex)
- [x] 2.7. [`kukavica`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kukavica.tex)
- [x] 2.8. [`vinar`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vinar.tex)
- [x] 2.9. [`razdaljeclp`](https://github.com/jaanos/or-zbirka/blob/master/naloge/razdaljeclp.tex)
- [x] 2.10. [`kromaticno`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kromaticno.tex)
- [x] 2.11. [`tsp`](https://github.com/jaanos/or-zbirka/blob/master/naloge/tsp.tex)
- [x] 2.12. [`vpetodrevo`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vpetodrevo.tex)
- [x] 2.13. [`asistenti`](https://github.com/jaanos/or-zbirka/blob/master/naloge/asistenti.tex)
- [x] 2.14. [`opravila`](https://github.com/jaanos/or-zbirka/blob/master/naloge/opravila.tex) (72a6c8a)
- [x] 2.15. [`polnjenje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/polnjenje.tex) (f2cf121)
- [x] 2.16. [`youtube`](https://github.com/jaanos/or-zbirka/blob/master/naloge/youtube.tex) (72a6c8a)
- [x] 2.17. [`sadje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/sadje.tex) (e6ae72c)
- [x] 2.18. [`dodelitev`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dodelitev.tex) (b12421a)
- [x] 2.19. [`linija`](https://github.com/jaanos/or-zbirka/blob/master/naloge/linija.tex) (bc54df4)
- [x] 2.20. [`nogomet`](https://github.com/jaanos/or-zbirka/blob/master/naloge/nogomet.tex) (3486100)
- [x] 2.21. [`ceki`](https://github.com/jaanos/or-zbirka/blob/master/naloge/ceki.tex) (5dad22e)
- [x] 2.22. [`kosarka`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kosarka.tex) - @RenkoT97 (#29)
- [x] 2.23. [`mostovi`](https://github.com/jaanos/or-zbirka/blob/master/naloge/mostovi.tex) (72a6c8a)
- [x] 2.24. [`vinar2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vinar2.tex) (72a6c8a)
- [x] 2.25. [`minolovec`](https://github.com/jaanos/or-zbirka/blob/master/naloge/minolovec.tex) (9f422b6)
- [x] 2.26. [`skatle`](https://github.com/jaanos/or-zbirka/blob/master/naloge/skatle.tex) (7abb054)
- [x] 2.27. [`drazba`](https://github.com/jaanos/or-zbirka/blob/master/naloge/drazba.tex)
- [x] 2.28. [`vsotakvadratov`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vsotakvadratov.tex) (6b58a25)
- [x] 2.29. [`tovor`](https://github.com/jaanos/or-zbirka/blob/master/naloge/tovor.tex) (bc38273)
- [x] 2.30. [`stevila`](https://github.com/jaanos/or-zbirka/blob/master/naloge/stevila.tex) (89fc7b3)
- [x] 2.31. [`nijke`](https://github.com/jaanos/or-zbirka/blob/master/naloge/nijke.tex) (bd48d14)
- [x] 2.32. [`crnko`](https://github.com/jaanos/or-zbirka/blob/master/naloge/crnko.tex) - @RenkoT97 (#28)
- [x] 2.33. [`kopalec`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kopalec.tex) - @RenkoT97 (#27)
- [x] 2.34. [`maxminprirejanje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/maxminprirejanje.tex) (0f5ad72)
- [x] 2.35. [`pakiranje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pakiranje.tex) (d524c87)
- [x] 2.36. [`uravnotezeno`](https://github.com/jaanos/or-zbirka/blob/master/naloge/uravnotezeno.tex) (49952f3)
- [x] 2.37. [`fgh`](https://github.com/jaanos/or-zbirka/blob/master/naloge/fgh.tex) (ca44df4)
- [x] 2.38. [`f1f2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/f1f2.tex) (644e963)
- [x] 2.39. [`sudoku`](https://github.com/jaanos/or-zbirka/blob/master/naloge/sudoku.tex) (eb1f12c)
- [x] 2.40. [`turnir`](https://github.com/jaanos/or-zbirka/blob/master/naloge/turnir.tex) (d63b1fd)
- [x] 2.41. [`oblacila`](https://github.com/jaanos/or-zbirka/blob/master/naloge/oblacila.tex) (9b7c822)
- [x] 2.42. [`festival`](https://github.com/jaanos/or-zbirka/blob/master/naloge/festival.tex) (9e80b6d)
- [x] 2.43. [`karantena`](https://github.com/jaanos/or-zbirka/blob/master/naloge/karantena.tex) (3bd77b4)
- [x] 2.44. [`licence`](https://github.com/jaanos/or-zbirka/blob/master/naloge/licence.tex) (#49)
- [x] 2.45. [`kuponi`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kuponi.tex) (#55)

Če bi kdo rad rešil katero nalogo, naj prosim odgovori na ta issue in si jo tako rezervira.

**Comment by janimetez** [comment]
Pozdravljeni, rezerviral bi nalogo 2.22. kosarka. Hvala

**Comment by jaanos** [comment]
Hvala @janimetez, imaš rezervirano.

**Comment by enejkovac** [comment]
Pozdravljeni, rezerviral bi 2.39, sudoku.
Hvala

**Comment by jaanos** [comment]
Hvala @enejkovac, imaš rezervirano.

**Comment by TjasaRen** [comment]
Pozdravljeni,
Rezervirala bi nalogo 2.33, kopalec.
Hvala

**Comment by jaanos** [comment]
Hvala @RenkoT97, imaš rezervirano.

**Comment by TjasaRen** [comment]
Pozdravljeni,
Rezervirala bi nalogo 2.32, Črnko.
Hvala

**Comment by jaanos** [comment]
Hvala, imaš rezervirano.

**Comment by TjasaRen** [comment]
Pozdravljeni,
Rezervirala bi nalogo 2.22, košarka.
Hvala

**Comment by jaanos** [comment]
@RenkoT97, imaš rezervirano nalogo 2.22.
