### ISSUE TITLE
Rešitve nalog iz razdelka 3: Teorija odločanja

### ISSUE THREAD

**Issue by jaanos** [jaanos/or-zbirka#3]
- [x] 3.1. [`kovanec`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kovanec.tex)
- [x] 3.2. [`zemljice`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zemljice.tex)
- [x] 3.3. [`operacija`](https://github.com/jaanos/or-zbirka/blob/master/naloge/operacija.tex)
- [x] 3.4. [`produkt`](https://github.com/jaanos/or-zbirka/blob/master/naloge/produkt.tex)
- [x] 3.5. [`koncert`](https://github.com/jaanos/or-zbirka/blob/master/naloge/koncert.tex)
- [x] 3.6. [`rexhep`](https://github.com/jaanos/or-zbirka/blob/master/naloge/rexhep.tex)
- [x] 3.7. [`dectree`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dectree.tex)
- [x] 3.8. [`avtobus`](https://github.com/jaanos/or-zbirka/blob/master/naloge/avtobus.tex)
- [x] 3.9. [`konkurenca`](https://github.com/jaanos/or-zbirka/blob/master/naloge/konkurenca.tex) (72a6c8a)
- [x] 3.10. [`poker`](https://github.com/jaanos/or-zbirka/blob/master/naloge/poker.tex) (72a6c8a)
- [x] 3.11. [`dectree2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dectree2.tex) (4695171)
- [x] 3.12. [`podjetnik`](https://github.com/jaanos/or-zbirka/blob/master/naloge/podjetnik.tex) (91a34fd)
- [x] 3.13. [`vrac`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vrac.tex) (21f44d2)
- [x] 3.14. [`dectree3`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dectree3.tex) - @evadezelak (#20)
- [x] 3.15. [`ajkalaj`](https://github.com/jaanos/or-zbirka/blob/master/naloge/ajkalaj.tex)
- [x] 3.16. [`bp`](https://github.com/jaanos/or-zbirka/blob/master/naloge/bp.tex) (84e50cc)
- [x] 3.17. [`rabljenoletalo`](https://github.com/jaanos/or-zbirka/blob/master/naloge/rabljenoletalo.tex) (b224c32)
- [x] 3.18. [`drugastopnja`](https://github.com/jaanos/or-zbirka/blob/master/naloge/drugastopnja.tex) (591663d)
- [x] 3.19. [`direktorica`](https://github.com/jaanos/or-zbirka/blob/master/naloge/direktorica.tex) (6c3c020)
- [x] 3.20. [`vezava`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vezava.tex)
- [x] 3.21. [`letalskekarte`](https://github.com/jaanos/or-zbirka/blob/master/naloge/letalskekarte.tex) (7abb054)
- [x] 3.22. [`fenko`](https://github.com/jaanos/or-zbirka/blob/master/naloge/fenko.tex) - @mperbil (#38)
- [x] 3.23. [`ljubo`](https://github.com/jaanos/or-zbirka/blob/master/naloge/ljubo.tex) (8881e3d)
- [x] 3.24. [`tovarna`](https://github.com/jaanos/or-zbirka/blob/master/naloge/tovarna.tex) - @zalastopar, @Babnik21 (#32)
- [x] 3.25. [`zlatnik`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zlatnik.tex) (ac07365)
- [x] 3.26. [`lunaairways`](https://github.com/jaanos/or-zbirka/blob/master/naloge/lunaairways.tex) - @JanSifrer (#34)
- [x] 3.27. [`maphija`](https://github.com/jaanos/or-zbirka/blob/master/naloge/maphija.tex) - @zalastopar, @Babnik21 (#33)
- [x] 3.28. [`judo`](https://github.com/jaanos/or-zbirka/blob/master/naloge/judo.tex) - @JanSifrer (#35)
- [x] 3.29. [`sok`](https://github.com/jaanos/or-zbirka/blob/master/naloge/sok.tex) (d63b1fd)
- [x] 3.30. [`cokolada`](https://github.com/jaanos/or-zbirka/blob/master/naloge/cokolada.tex) (9b7c822)
- [x] 3.31. [`dectree4`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dectree4.tex) (613c4bd)
- [x] 3.32. [`trajekt`](https://github.com/jaanos/or-zbirka/blob/master/naloge/trajekt.tex) (6e6f179)
- [x] 3.33. [`zemlja`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zemlja.tex) (#49)
- [x] 3.34. [`zemlja2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zemlja2.tex) (#49)

Če bi kdo rad rešil katero nalogo, naj prosim odgovori na ta issue in si jo tako rezervira.

**Comment by matejske** [comment]
Rezerviral bi si naloge: 
- 3.9. konkurenca
- 3.14. dectree3
- 3.21. letalske karte

**Comment by jaanos** [comment]
Hvala @matejske, sem te zaenkrat pisal pri nalogi 3.9. Bi namreč prosil, da si rezervirate eno nalogo naenkrat - bom še posodobil navodila na spletni učilnici.

**Comment by larajagodnik** [comment]
Pozdravljeni, rezervirala bi nalogo 3.11 dectree2. Hvala

**Comment by jaanos** [comment]
Hvala @larajagodnik, imaš rezervirano.

**Comment by evadezelak** [comment]
Pozdravljeni, rezervirala bi nalogo 3.14. Hvala

**Comment by jaanos** [comment]
@evadezelak, imaš rezervirano nalogo 3.14.

**Comment by zalastopar** [comment]
Pozdravljeni, jaz in @Babnik21 bi si za skupinsko reševanje rezervirala nalogi 3.24 in 3.27

**Comment by jaanos** [comment]
Hvala @zalastopar in @Babnik21, imata rezervirani obe nalogi.

**Comment by JanSifrer** [comment]
Pozdravljeni, rezerviral bi nalogo 3.26. lunaairways.

**Comment by jaanos** [comment]
Hvala @JanSifrer, imaš rezervirano.

**Comment by JanSifrer** [comment]
Pozdravljeni, rezerviral bi nalogo 3.28. judo.
Hvala

**Comment by jaanos** [comment]
@JanSifrer, imaš rezervirano nalogo 3.28.

**Comment by mperbil** [comment]
Pozdravljeni, rezerviral bi nalogo 3.22.

**Comment by jaanos** [comment]
Hvala @mperbil, imaš rezervirano.
