### ISSUE TITLE
Rešitve nalog iz razdelka 4: Dinamično programiranje

### ISSUE THREAD

**Issue by jaanos** [jaanos/or-zbirka#4]
- [x] 4.1. [`plakati`](https://github.com/jaanos/or-zbirka/blob/master/naloge/plakati.tex) (0d2335b)
- [x] 4.2. [`nahrbtnik`](https://github.com/jaanos/or-zbirka/blob/master/naloge/nahrbtnik.tex) (0d2335b)
- [x] 4.3. [`matrika`](https://github.com/jaanos/or-zbirka/blob/master/naloge/matrika.tex) (0d2335b)
- [x] 4.4. [`strnjenpodniz`](https://github.com/jaanos/or-zbirka/blob/master/naloge/strnjenpodniz.tex) (0d2335b)
- [x] 4.5. [`strnjenapodmatrika`](https://github.com/jaanos/or-zbirka/blob/master/naloge/strnjenapodmatrika.tex) (b68d86e)
- [x] 4.6. [`kovanci`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kovanci.tex) (b68d86e)
- [x] 4.7. [`tat`](https://github.com/jaanos/or-zbirka/blob/master/naloge/tat.tex) (b68d86e)
- [x] 4.8. [`hlod`](https://github.com/jaanos/or-zbirka/blob/master/naloge/hlod.tex) (b68d86e)
- [x] 4.9. [`jagode`](https://github.com/jaanos/or-zbirka/blob/master/naloge/jagode.tex) (1ce81a6)
- [x] 4.10. [`marketing`](https://github.com/jaanos/or-zbirka/blob/master/naloge/marketing.tex) (1ce81a6)
- [x] 4.11. [`boltezar`](https://github.com/jaanos/or-zbirka/blob/master/naloge/boltezar.tex) (1ce81a6)
- [x] 4.12. [`ucbeniki`](https://github.com/jaanos/or-zbirka/blob/master/naloge/ucbeniki.tex) (1ce81a6)
- [x] 4.13. [`nelinearni`](https://github.com/jaanos/or-zbirka/blob/master/naloge/nelinearni.tex) (1ce81a6)
- [x] 4.14. [`hazarder`](https://github.com/jaanos/or-zbirka/blob/master/naloge/hazarder.tex) (1ce81a6)
- [x] 4.15. [`blago`](https://github.com/jaanos/or-zbirka/blob/master/naloge/blago.tex) (#41)
- [x] 4.16. [`blago2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/blago2.tex) (#41)
- [x] 4.17. [`strnjenprodukt`](https://github.com/jaanos/or-zbirka/blob/master/naloge/strnjenprodukt.tex) (72a6c8a)
- [x] 4.18. [`oscilirajoce`](https://github.com/jaanos/or-zbirka/blob/master/naloge/oscilirajoce.tex) (#42)
- [x] 4.19. [`aplikacija`](https://github.com/jaanos/or-zbirka/blob/master/naloge/aplikacija.tex) (72a6c8a)
- [x] 4.20. [`lobisti`](https://github.com/jaanos/or-zbirka/blob/master/naloge/lobisti.tex) (#45)
- [x] 4.21. [`domine`](https://github.com/jaanos/or-zbirka/blob/master/naloge/domine.tex) (e9c24b8)
- [x] 4.22. [`vlagatelj`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vlagatelj.tex) (#45)
- [x] 4.23. [`pocivalisca`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pocivalisca.tex) (#44)
- [x] 4.24. [`neznan`](https://github.com/jaanos/or-zbirka/blob/master/naloge/neznan.tex) (#43)
- [x] 4.25. [`pohlepar`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pohlepar.tex) (#45)
- [x] 4.26. [`jatifi`](https://github.com/jaanos/or-zbirka/blob/master/naloge/jatifi.tex) (#45)
- [x] 4.27. [`rekurzija`](https://github.com/jaanos/or-zbirka/blob/master/naloge/rekurzija.tex) (#42)
- [x] 4.28. [`prodajalec`](https://github.com/jaanos/or-zbirka/blob/master/naloge/prodajalec.tex) (#43)
- [x] 4.29. [`stiskanje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/stiskanje.tex) (#43)
- [x] 4.30. [`kocke`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kocke.tex) (#43)
- [x] 4.31. [`dnk`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dnk.tex) (#43)
- [x] 4.32. [`simboli`](https://github.com/jaanos/or-zbirka/blob/master/naloge/simboli.tex) (#43)
- [x] 4.33. [`stekelce`](https://github.com/jaanos/or-zbirka/blob/master/naloge/stekelce.tex) (72a6c8a)
- [x] 4.34. [`spust`](https://github.com/jaanos/or-zbirka/blob/master/naloge/spust.tex) (#42)
- [x] 4.35. [`antonio`](https://github.com/jaanos/or-zbirka/blob/master/naloge/antonio.tex) (#45)
- [x] 4.36. [`razdelitev`](https://github.com/jaanos/or-zbirka/blob/master/naloge/razdelitev.tex) (7abb054)
- [x] 4.37. [`plezanje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/plezanje.tex) (#42)
- [x] 4.38. [`igra`](https://github.com/jaanos/or-zbirka/blob/master/naloge/igra.tex) (#42)
- [x] 4.39. [`ovce`](https://github.com/jaanos/or-zbirka/blob/master/naloge/ovce.tex) (#45)
- [x] 4.40. [`delavci`](https://github.com/jaanos/or-zbirka/blob/master/naloge/delavci.tex) (#45)
- [x] 4.41. [`turkmenscina`](https://github.com/jaanos/or-zbirka/blob/master/naloge/turkmenscina.tex) (#43)
- [x] 4.42. [`hierarhija`](https://github.com/jaanos/or-zbirka/blob/master/naloge/hierarhija.tex) (#42)
- [x] 4.43. [`maxvsota`](https://github.com/jaanos/or-zbirka/blob/master/naloge/maxvsota.tex) - @kuco23 (#14)
- [x] 4.44. [`skoki`](https://github.com/jaanos/or-zbirka/blob/master/naloge/skoki.tex) - @kuco23 (#16)
- [x] 4.45. [`enice`](https://github.com/jaanos/or-zbirka/blob/master/naloge/enice.tex) (#42)
- [x] 4.46. [`investicije`](https://github.com/jaanos/or-zbirka/blob/master/naloge/investicije.tex) (1ce81a6)
- [x] 4.47. [`signal`](https://github.com/jaanos/or-zbirka/blob/master/naloge/signal.tex) (5d2833e)
- [x] 4.48. [`vodovod`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vodovod.tex) (2e7f2b3)
- [x] 4.49. [`matskoki`](https://github.com/jaanos/or-zbirka/blob/master/naloge/matskoki.tex) (90cddf4)
- [x] 4.50. [`vlagatelj2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vlagatelj2.tex) (ee6834b)
- [x] 4.51. [`stebri`](https://github.com/jaanos/or-zbirka/blob/master/naloge/stebri.tex) (#49)

Če bi kdo rad rešil katero nalogo, naj prosim odgovori na ta issue in si jo tako rezervira.

**Comment by kuco23** [comment]
Si lahko rezerviram nalogo 4.43?

**Comment by jaanos** [comment]
@kuco23, imaš rezervirano.

**Comment by kuco23** [comment]
rezerviral bi nalogo 4.44. Hvala.

**Comment by jaanos** [comment]
@kuco23, imaš rezervirano nalogo 4.44.
