### ISSUE TITLE
Popravek pri nalogi 2.17

### ISSUE THREAD

**Issue by MatejRojec** [jaanos/or-zbirka#48]
Zdi se mi, da bi morali biti pogoji za spremenljivke $x_i$,$y_i$,$z_i$ podani takole:
$\forall i \in \{ 1,...,n \} : x_i \geq 0 , x_i \in \mathbb{Z}$,
eanko potem tudi za $y_i$ in $z_i$.

**Comment by jaanos** [comment]
Res je, hvala! Sem popravil.
