### ISSUE TITLE
Rešitve nalog iz razdelka 5: Algoritmi na grafih

### ISSUE THREAD

**Issue by jaanos** [jaanos/or-zbirka#5]
- [x] 5.1. [`matgraf`](https://github.com/jaanos/or-zbirka/blob/master/naloge/matgraf.tex) (a1ddc0b)
- [x] 5.2. [`sosgraf`](https://github.com/jaanos/or-zbirka/blob/master/naloge/sosgraf.tex) (a1ddc0b)
- [x] 5.3. [`digraf`](https://github.com/jaanos/or-zbirka/blob/master/naloge/digraf.tex) (a1ddc0b)
- [x] 5.4. [`trikotnik`](https://github.com/jaanos/or-zbirka/blob/master/naloge/trikotnik.tex) (a1ddc0b)
- [x] 5.5. [`zvezda`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zvezda.tex) (a1ddc0b)
- [x] 5.6. [`bfs`](https://github.com/jaanos/or-zbirka/blob/master/naloge/bfs.tex) - @evadezelak (#10)
- [x] 5.7. [`premer`](https://github.com/jaanos/or-zbirka/blob/master/naloge/premer.tex) (96bec62)
- [x] 5.8. [`dijkstra`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dijkstra.tex) - @evadezelak (#17)
- [x] 5.9. [`negdijkstra`](https://github.com/jaanos/or-zbirka/blob/master/naloge/negdijkstra.tex) - @kuco23 (#22)
- [x] 5.10. [`avto`](https://github.com/jaanos/or-zbirka/blob/master/naloge/avto.tex) (96bec62)
- [x] 5.11. [`dijkstra2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dijkstra2.tex) (96bec62)
- [x] 5.12. [`dfs`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dfs.tex) - @evadezelak (#12)
- [x] 5.13. [`bf`](https://github.com/jaanos/or-zbirka/blob/master/naloge/bf.tex) (e1682ef)
- [x] 5.14. [`topo`](https://github.com/jaanos/or-zbirka/blob/master/naloge/topo.tex) - @kuco23 (#11, #13)
- [x] 5.15. [`oviratlon`](https://github.com/jaanos/or-zbirka/blob/master/naloge/oviratlon.tex) (e1682ef)
- [x] 5.16. [`topoclp`](https://github.com/jaanos/or-zbirka/blob/master/naloge/topoclp.tex) (#46)
- [x] 5.17. [`vectopo`](https://github.com/jaanos/or-zbirka/blob/master/naloge/vectopo.tex) (#46)
- [x] 5.18. [`zaklad`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zaklad.tex) (699a95b)
- [x] 5.19. [`razdalje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/razdalje.tex) - @kuco23 (#18)
- [x] 5.20. [`pocitnice`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pocitnice.tex) (#44)
- [x] 5.21. [`prerezna`](https://github.com/jaanos/or-zbirka/blob/master/naloge/prerezna.tex) (#46)
- [x] 5.22. [`dag`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dag.tex) - @kuco23 (#26)
- [x] 5.23. [`pot`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pot.tex) - @evadezelak (#25)
- [x] 5.24. [`trditve`](https://github.com/jaanos/or-zbirka/blob/master/naloge/trditve.tex) (#46)
- [x] 5.25. [`fw`](https://github.com/jaanos/or-zbirka/blob/master/naloge/fw.tex) (#50)
- [x] 5.26. [`nesrece`](https://github.com/jaanos/or-zbirka/blob/master/naloge/nesrece.tex)
- [x] 5.27. [`poslovnez`](https://github.com/jaanos/or-zbirka/blob/master/naloge/poslovnez.tex) - @juresternad (#54)
- [x] 5.28. [`trditve2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/trditve2.tex) (#46)
- [x] 5.29. [`lenoritas`](https://github.com/jaanos/or-zbirka/blob/master/naloge/lenoritas.tex) (#58)
- [x] 5.30. [`letalisce`](https://github.com/jaanos/or-zbirka/blob/master/naloge/letalisce.tex) (#44)
- [x] 5.31. [`stpoti`](https://github.com/jaanos/or-zbirka/blob/master/naloge/stpoti.tex) (#46)
- [x] 5.32. [`otoki`](https://github.com/jaanos/or-zbirka/blob/master/naloge/otoki.tex) (#44)
- [x] 5.33. [`cesta`](https://github.com/jaanos/or-zbirka/blob/master/naloge/cesta.tex) (#44)
- [x] 5.34. [`delegati`](https://github.com/jaanos/or-zbirka/blob/master/naloge/delegati.tex) (#58)
- [x] 5.35. [`cmrlji`](https://github.com/jaanos/or-zbirka/blob/master/naloge/cmrlji.tex) (#58)
- [x] 5.36. [`zabe`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zabe.tex) - @kuco23 (#23)
- [x] 5.37. [`optika`](https://github.com/jaanos/or-zbirka/blob/master/naloge/optika.tex) (#58)
- [x] 5.38. [`pog`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pog.tex) (#46)
- [x] 5.39. [`omrezje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/omrezje.tex) (#58)
- [x] 5.40. [`marco`](https://github.com/jaanos/or-zbirka/blob/master/naloge/marco.tex) (#46)
- [x] 5.41. [`obnova`](https://github.com/jaanos/or-zbirka/blob/master/naloge/obnova.tex) (#58)
- [x] 5.42. [`cikel`](https://github.com/jaanos/or-zbirka/blob/master/naloge/cikel.tex) - @kuco23 (#24)
- [x] 5.43. [`studij`](https://github.com/jaanos/or-zbirka/blob/master/naloge/studij.tex) (#47)
- [x] 5.44. [`alternirajoca`](https://github.com/jaanos/or-zbirka/blob/master/naloge/alternirajoca.tex) (9b7c822)
- [x] 5.45. [`neodvisna`](https://github.com/jaanos/or-zbirka/blob/master/naloge/neodvisna.tex) (9b7c822)
- [x] 5.46. [`operaterji`](https://github.com/jaanos/or-zbirka/blob/master/naloge/operaterji.tex) (db23e55)
- [x] 5.47. [`stnajkrajsih`](https://github.com/jaanos/or-zbirka/blob/master/naloge/stnajkrajsih.tex) (9d85d9b)
- [x] 5.48. [`jadrnica`](https://github.com/jaanos/or-zbirka/blob/master/naloge/jadrnica.tex) (56ac1b1)
- [x] 5.49. [`najvect`](https://github.com/jaanos/or-zbirka/blob/master/naloge/najvect.tex) (#55)
- [x] 5.50. [`prirejanje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/prirejanje.tex) (#55)

Če bi kdo rad rešil katero nalogo, naj prosim odgovori na ta issue in si jo tako rezervira.

**Comment by evadezelak** [comment]
Pozdravljeni, rezervirala bi si nalogo 5.6. Hvala

**Comment by jaanos** [comment]
Hvala @evadezelak, imaš rezervirano.

**Comment by kuco23** [comment]
Pozdravljeni, rezerviral bi si nalogo 5.14.

**Comment by jaanos** [comment]
Hvala @kuco23, imaš rezervirano.

**Comment by evadezelak** [comment]
Pozdravljeni, rezervirala bi nalogo 5.12. Hvala

**Comment by jaanos** [comment]
@evadezelak, imaš rezervirano.

**Comment by evadezelak** [comment]
Pozdravljeni, rezervirala bi nalogo 5.8. Hvala

**Comment by jaanos** [comment]
@evadezelak, imaš rezervirano nalogo 5.8.

**Comment by jaanos** [comment]
Sem nekoliko še posodobil [navodila](https://github.com/jaanos/or-zbirka/blob/master/STRUCTURE.md#drugo) za pisanje psevdokode, tako da bi prosil, da se jih držite (sem tudi sam naredil nekaj sprememb, da se poenoti uporaba).

Glede na to, da sedaj imamo spisane algoritme `bfs`, `dfs` in `Topo` (ter pričakujemo še `Dijkstra`), se lahko ostale naloge sklicujejo nanje, npr.
```LaTeX
Uporabimo algoritem {\sc bfs} iz naloge~\res[bfs].
```
Tako se algoritmi ne bodo ponavljali.

@evadezelak, predlagam, da pri nalogi 5.8 napišeš samo osnovni Dijkstrov algoritem, brez psevdokode za uporabljene strukture (npr. kopico). Najbolje bo, da kar sinhroniziraš svojo vejo `master` s tem repozitorijem in od tam začneš novo vejo.

**Comment by kuco23** [comment]
Rezerviral bi nalogo 5.19. Hvala

**Comment by jaanos** [comment]
@kuco23, imaš rezervirano nalogo 5.19.

**Comment by kuco23** [comment]
bi lahko reševal nalogo 5.9?

**Comment by jaanos** [comment]
Lahko - kot sem pa ti napisal @kuco23, to ne bo uradna rezervacija, tako da če se še kdo drug javi za isto nalogo, ima prednost.

**Comment by kuco23** [comment]
bi lahko reševal nalogo 5.35?

**Comment by jaanos** [comment]
Seveda @kuco23, kar reši.

**Comment by evadezelak** [comment]
Pozdravljeni, rezervirala bi nalogo 5.23. Hvala

**Comment by jaanos** [comment]
@evadezelak, imaš rezervirano nalogo 5.23.

**Comment by kuco23** [comment]
bi lahko rešil nalogo 5.41?

**Comment by jaanos** [comment]
@kuco23, kar reši.

**Comment by kuco23** [comment]
bi lahko rešil 5.22 ?

**Comment by jaanos** [comment]
Seveda @kuco23, kar reši.

**Comment by juresternad** [comment]
Pozdravljeni, prosil bi za rezervacijo naloge 5.6. Hvala

**Comment by jaanos** [comment]
@juresternad, naloga 5.6. že ima rešitev. Rezerviraš si lahko naloge, ki še nimajo rešitve - v zgornjem seznamu so neobkljukane.

Če pa najdeš kakršnokoli napako pri obstoječih rešitvah, lahko kar pošlješ popravek (rezervacija ni potrebna).

**Comment by juresternad** [comment]
Mislil sem nalogo 5.27

**Comment by jaanos** [comment]
Velja @juresternad, imaš rezervirano.
