### ISSUE TITLE
Napaka v navodilu

### ISSUE THREAD

**Issue by vitorozman** [jaanos/or-zbirka#52]
Pri nalogi 5.43 je napak v navodilu. 
V _Tabela 2: Podatki za nalogo 5.43._ je za predmet (oznako) _h_ zadosten pogoj narobe naveden, predmet _h_ je zadosten pogoj za _h_, kar je malo nesmiselno. Vrjetno bi moral biti zadosten pogoj za _g_, saj tako dobim enak rezultat kot je v rešitvah.

**Comment by jaanos** [comment]
Res je, hvala! Do napake je prišlo v cc1f8d79f10b3529a64e6fe93fc33b0a971b8d37, ko sem zamenjal velike črke z malimi. Sem sedaj popravil.
