### ISSUE TITLE
Napaka v rešitvi pri nalogi 2.7

### ISSUE THREAD

**Issue by juresternad** [jaanos/or-zbirka#56]
V rešitvi je kot iskana vrednost naveden maksimum vsote samo po i-jih: $max(\sum_{i=1}^{12} j p_{ij} x_{ij}$). Mislim, da bi morala biti vključena še vsota po j-jih: $max(\sum_{i=1}^{12} (\sum_{j=1}^3 j p_{ij} x_{ij}))$.

Prav tako ni naveden pogoj:$\forall i = 1, \dots, 12, \forall j = 1, 2, 3: 0 \le x_{ij} \le 1, x_{ij} \in \mathbb{Z}$

**Comment by jaanos** [comment]
Res je, hvala! Sem popravil (bom pridružil v glavno vejo v kratkem).
