### ISSUE TITLE
Napaka v rešitvi naloge 3.11

### ISSUE THREAD

**Issue by juresternad** [jaanos/or-zbirka#57]
Na koncu rešitve je podan postopek odločanja: 

• Če je 0 ≤ p < 3/22, se odločimo za pot preko vozlišča C v list z vrednostjo 0.
• Če je 1/7  ≤ p < 3/22, se odločimo za pot preko vozlišča B.

Mislim, da je v drugem primeru pravi interval: 3/22 ≤  p ≤ 1/4.

**Comment by jaanos** [comment]
Res je, hvala! Sem popravil.
