### ISSUE TITLE
Rešitve nalog iz razdelka 6: CPM/PERT

### ISSUE THREAD

**Issue by jaanos** [jaanos/or-zbirka#6]
- [x] 6.1. [`brezzobec`](https://github.com/jaanos/or-zbirka/blob/master/naloge/brezzobec.tex) (92bf5b7)
- [x] 6.2. [`brezzobec-lp`](https://github.com/jaanos/or-zbirka/blob/master/naloge/brezzobec-lp.tex) (2b9ef88)
- [x] 6.3. [`palacinke`](https://github.com/jaanos/or-zbirka/blob/master/naloge/palacinke.tex) (2b9ef88)
- [x] 6.4. [`palacinke1`](https://github.com/jaanos/or-zbirka/blob/master/naloge/palacinke1.tex) (28822b6)
- [x] 6.5. [`palacinke2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/palacinke2.tex) (2b9ef88)
- [x] 6.6. [`viadukt`](https://github.com/jaanos/or-zbirka/blob/master/naloge/viadukt.tex) (2b9ef88)
- [x] 6.7. [`splet`](https://github.com/jaanos/or-zbirka/blob/master/naloge/splet.tex) (72a6c8a)
- [x] 6.8. [`konferenca`](https://github.com/jaanos/or-zbirka/blob/master/naloge/konferenca.tex) - @AnjaTrobec (#40)
- [x] 6.9. [`letalo`](https://github.com/jaanos/or-zbirka/blob/master/naloge/letalo.tex) (#44)
- [x] 6.10. [`objekt`](https://github.com/jaanos/or-zbirka/blob/master/naloge/objekt.tex) - @JanSifrer (#37)
- [x] 6.11. [`naselje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/naselje.tex) (e1a3edb)
- [x] 6.12. [`avtocesta`](https://github.com/jaanos/or-zbirka/blob/master/naloge/avtocesta.tex) (8695125)
- [x] 6.13. [`dirka`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dirka.tex) (#55)
- [x] 6.14. [`dirka2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/dirka2.tex) (#55)

Če bi kdo rad rešil katero nalogo, naj prosim odgovori na ta issue in si jo tako rezervira.

**Comment by JanSifrer** [comment]
Pozdravljeni, 
rad bi rezerviral nalogo 6.10. `objekt`.
Hvala

**Comment by jaanos** [comment]
@JanSifrer, imaš rezervirano nalogo 6.10.

**Comment by AnjaTrobec** [comment]
Živjo, rezervirala bi konferenco 6.8.
Hvala!

**Comment by jaanos** [comment]
Hvala @AnjaTrobec, imaš rezervirano.
