### ISSUE TITLE
Rešitve nalog iz razdelka 8: Pretoki in prerezi

### ISSUE THREAD

**Issue by jaanos** [jaanos/or-zbirka#8]
- [x] 8.1. [`minmaxpretok`](https://github.com/jaanos/or-zbirka/blob/master/naloge/minmaxpretok.tex) (586798f)
- [x] 8.2. [`minkapaciteta`](https://github.com/jaanos/or-zbirka/blob/master/naloge/minkapaciteta.tex) (c3851df)
- [x] 8.3. [`lenority`](https://github.com/jaanos/or-zbirka/blob/master/naloge/lenority.tex) (68a7ab2)
- [x] 8.4. [`pretokx`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pretokx.tex) (f801430)
- [x] 8.5. [`terminali`](https://github.com/jaanos/or-zbirka/blob/master/naloge/terminali.tex) (c5cd542)
- [x] 8.6. [`greedyflow`](https://github.com/jaanos/or-zbirka/blob/master/naloge/greedyflow.tex) (fc9b54f)
- [x] 8.7. [`minprerezi`](https://github.com/jaanos/or-zbirka/blob/master/naloge/minprerezi.tex) (ac68bfb)
- [x] 8.8. [`kri`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kri.tex) (b06ac72)
- [x] 8.9. [`kri2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/kri2.tex) (54b02d1)
- [x] 8.10. [`zajetje`](https://github.com/jaanos/or-zbirka/blob/master/naloge/zajetje.tex) (86c57fd)
- [x] 8.11. [`divjizur`](https://github.com/jaanos/or-zbirka/blob/master/naloge/divjizur.tex) (0c834bb)
- [x] 8.12. [`mafija`](https://github.com/jaanos/or-zbirka/blob/master/naloge/mafija.tex) (f8d68ff)
- [x] 8.13. [`rovi`](https://github.com/jaanos/or-zbirka/blob/master/naloge/rovi.tex) (a342f56)
- [x] 8.14. [`strezniki`](https://github.com/jaanos/or-zbirka/blob/master/naloge/strezniki.tex) (e8f64e9)
- [x] 8.15. [`pretok1`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pretok1.tex)
- [x] 8.16. [`pretok2`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pretok2.tex)
- [x] 8.17. [`pretok3`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pretok3.tex)
- [x] 8.18. [`pretok4`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pretok4.tex)
- [x] 8.19. [`pretok5`](https://github.com/jaanos/or-zbirka/blob/master/naloge/pretok5.tex)

Če bi kdo rad rešil katero nalogo, naj prosim odgovori na ta issue in si jo tako rezervira.

**Comment by matejske** [comment]
Rezerviral bi si nalogo:  8.1. minmaxpretok

**Comment by jaanos** [comment]
Kot rečeno v #3, bom počakal, da napišeš rešitev za rezervirano nalogo, pa boš potem sporočil, katero bi naslednjo reševal.
